apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: bronze
provisioner: kubernetes.io/azure-file
parameters:
  storageAccount: pnstandarddatastorage

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: silver
provisioner: kubernetes.io/azure-file
parameters:
  storageAccount: pnstandarddatastorage

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gold
provisioner: kubernetes.io/azure-file
parameters:
  storageAccount: pnstandarddatastorage
